/**
 * Proves the client-bundle check works end to end: plants secret-like values
 * in throwaway client code, builds that variant into an isolated directory and
 * requires the check to fail on it. Exit codes: 0 the check caught every
 * planted value, 1 it missed at least one, 2 setup failure.
 *
 *   node tools/planted-secret-check.ts [--keep]
 *
 * The fixture route is created under src/app only for the duration of the
 * run and removed afterwards; a leftover copy fails `npm test`
 * (tests/routes.test.ts) and the regular `npm run check:bundle`.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { serverOnlyVariableNames } from '../src/env/server-schema.ts';
import { checkClientBundle } from './client-bundle-check.ts';
import { formatFinding, type Finding } from './client-bundle-rules.ts';
import { planInvocation } from './timed.ts';

export const PLANTED_DIST_DIR = '.next/planted';
export const PLANTED_ROUTE_SEGMENT = 'planted-secret-fixture';
export const PLANTED_FIXTURE_DIR = path.join('src', 'app', '(customer)', PLANTED_ROUTE_SEGMENT);
export const PLANTED_ENVIRONMENT_VARIABLE = 'WEB_PLANTED_TOKEN';

/**
 * Secret-like literals for the fixture, one per detection rule. They are
 * assembled at runtime so this source file never contains a token-shaped
 * literal that repository or push-protection secret scanning would flag.
 */
export function plantedLiterals(): Readonly<Record<string, string>> {
  const encode = (value: object): string =>
    Buffer.from(JSON.stringify(value)).toString('base64url');
  return Object.freeze({
    'stripe-live-key': ['sk', 'live', 'PLANTEDFIXTURE0000000000'].join('_'),
    'aws-access-key-id': ['AKIA', 'PLANTEDFIXTURE00'].join(''),
    'json-web-token': [
      encode({ alg: 'none', typ: 'JWT' }),
      encode({ sub: 'planted-fixture', note: 'synthetic' }),
      'planted-fixture-signature',
    ].join('.'),
  });
}

function fixtureSources(literals: Readonly<Record<string, string>>): Record<string, string> {
  const items = Object.entries(literals)
    .map(
      ([rule, value]) =>
        `        <li data-rule=${JSON.stringify(rule)}>${JSON.stringify(value)}</li>`,
    )
    .join('\n');
  return {
    'planted-client.tsx': [
      "'use client';",
      '',
      '// Generated by tools/planted-secret-check.ts; never commit this file.',
      'export function PlantedClient() {',
      '  return (',
      '    <ul>',
      items,
      '    </ul>',
      '  );',
      '}',
      '',
    ].join('\n'),
    'page.tsx': [
      "import { PlantedClient } from './planted-client';",
      '',
      '// Generated by tools/planted-secret-check.ts; never commit this file.',
      `const leakedServerValue = process.env.${PLANTED_ENVIRONMENT_VARIABLE} ?? 'unset';`,
      '',
      'export default function PlantedPage() {',
      '  return (',
      '    <>',
      '      <h1>Planted secret fixture</h1>',
      '      <p>{leakedServerValue}</p>',
      '      <PlantedClient />',
      '    </>',
      '  );',
      '}',
      '',
    ].join('\n'),
  };
}

interface Expectation {
  readonly rule: Finding['rule'];
  readonly subject: string;
  readonly location: 'static/' | 'server/';
}

export function expectations(literals: Readonly<Record<string, string>>): Expectation[] {
  return [
    ...Object.keys(literals).map((subject): Expectation => ({
      rule: 'secret-pattern',
      subject,
      location: 'static/',
    })),
    { rule: 'secret-env-value', subject: PLANTED_ENVIRONMENT_VARIABLE, location: 'server/' },
  ];
}

export function missingExpectations(
  expected: readonly Expectation[],
  findings: readonly Finding[],
): Expectation[] {
  return expected.filter(
    (expectation) =>
      !findings.some(
        (finding) =>
          finding.rule === expectation.rule &&
          finding.subject === expectation.subject &&
          finding.file.startsWith(expectation.location),
      ),
  );
}

function writeFixture(literals: Readonly<Record<string, string>>): void {
  if (existsSync(PLANTED_FIXTURE_DIR)) {
    console.warn(`planted-secret-check: replacing leftover fixture at ${PLANTED_FIXTURE_DIR}`);
    removeFixture();
  }
  mkdirSync(PLANTED_FIXTURE_DIR, { recursive: true });
  for (const [name, content] of Object.entries(fixtureSources(literals))) {
    writeFileSync(path.join(PLANTED_FIXTURE_DIR, name), content, 'utf8');
  }
}

function removeFixture(): void {
  rmSync(PLANTED_FIXTURE_DIR, { recursive: true, force: true });
}

function buildPlantedVariant(plantedToken: string): number {
  const invocation = planInvocation('npx', ['next', 'build']);
  const result = spawnSync(invocation.command, [...invocation.args], {
    stdio: 'inherit',
    shell: invocation.shell,
    env: {
      ...process.env,
      NEXT_TELEMETRY_DISABLED: '1',
      WEB_BUILD_VARIANT: 'planted-secret-check',
      [PLANTED_ENVIRONMENT_VARIABLE]: plantedToken,
    },
  });
  if (result.error) {
    console.error(`planted-secret-check: could not start next build: ${result.error.message}`);
    return 2;
  }
  return result.status ?? 2;
}

export function main(argv: readonly string[]): number {
  const keep = argv.includes('--keep');
  const unknown = argv.filter((argument) => argument !== '--keep');
  if (unknown.length > 0) {
    console.error(`planted-secret-check: unknown argument(s): ${unknown.join(' ')}`);
    console.error('usage: node tools/planted-secret-check.ts [--keep]');
    return 2;
  }

  const literals = plantedLiterals();
  const plantedToken = `planted-${randomBytes(16).toString('hex')}`;
  const nextEnvFile = 'next-env.d.ts';
  const previousNextEnv = existsSync(nextEnvFile) ? readFileSync(nextEnvFile, 'utf8') : undefined;
  const cleanup = (): void => {
    removeFixture();
    // The planted build rewrites next-env.d.ts to point at its own type output.
    if (previousNextEnv === undefined) {
      rmSync(nextEnvFile, { force: true });
    } else {
      writeFileSync(nextEnvFile, previousNextEnv, 'utf8');
    }
    if (!keep) {
      rmSync(PLANTED_DIST_DIR, { recursive: true, force: true });
    }
  };
  const onSignal = (): void => {
    cleanup();
    process.exit(130);
  };
  process.once('SIGINT', onSignal);
  process.once('SIGTERM', onSignal);

  try {
    writeFixture(literals);
    console.log(
      `planted-secret-check: planted ${Object.keys(literals).length} literal(s) and ${PLANTED_ENVIRONMENT_VARIABLE} in ${PLANTED_FIXTURE_DIR}; building into ${PLANTED_DIST_DIR}`,
    );
    const buildStatus = buildPlantedVariant(plantedToken);
    if (buildStatus !== 0) {
      console.error(`planted-secret-check: planted build failed with exit ${buildStatus}`);
      return 2;
    }
    const result = checkClientBundle(PLANTED_DIST_DIR, {
      serverOnlyNames: serverOnlyVariableNames,
      environment: { ...process.env, [PLANTED_ENVIRONMENT_VARIABLE]: plantedToken },
    });
    if (result.artifacts === 0) {
      console.error(`planted-secret-check: no artifacts found under ${PLANTED_DIST_DIR}`);
      return 2;
    }
    const missing = missingExpectations(expectations(literals), result.findings);
    console.log(
      `planted-secret-check: bundle check reported ${result.findings.length} finding(s) across ${result.artifacts} artifact(s) (values withheld)`,
    );
    for (const finding of result.findings) {
      console.log(`  ${formatFinding(finding)}`);
    }
    if (result.findings.length === 0 || missing.length > 0) {
      console.error('planted-secret-check: FAILED; the bundle check did not report:');
      for (const expectation of missing) {
        console.error(
          `  ${expectation.rule} [${expectation.subject}] under ${expectation.location}`,
        );
      }
      return 1;
    }
    console.log(
      'planted-secret-check: passed; every planted client literal and the planted server value were caught',
    );
    return 0;
  } catch (error) {
    console.error(
      `planted-secret-check: ${error instanceof Error ? error.message : String(error)}`,
    );
    return 2;
  } finally {
    process.off('SIGINT', onSignal);
    process.off('SIGTERM', onSignal);
    cleanup();
  }
}

if (import.meta.main) {
  process.exitCode = main(process.argv.slice(2));
}
